
@baseUrl = http://localhost:3333

### Add a category
POST {{ baseUrl }}/categories
Content-Type: application/json

{
  "name": "Category name",
  "description": "Category description"
}
 

### List all category
GET {{ baseUrl }}/categories
Content-Type: application/json

 


### Add a product
  
 