
@baseUrl = http://localhost:3333

### Add a category
POST {{ baseUrl }}/categories
Content-Type: application/json

{
  "name": "Category name",
  "description": "Category description"
}
 

### List all category
GET {{ baseUrl }}/categories
Content-Type: application/json

 

### Add a specficitaion
POST {{ baseUrl }}/specification
Content-Type: application/json

{
  "name": "Spec name s",
  "description": "Spec description"
}
 

### List all specficitaion
GET {{ baseUrl }}/specification
Content-Type: application/json
