# 
version: '2.13'

services:
  app:
    build: .
    container_name: rentex
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app


# seee the log 
# docker logs -f rentex
