# 
version: '2.13'

services:
  db:
    image: postgres
    container_name: rentex_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rentex
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentex
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata: 
    driver: local
# seee the log 
# docker logs -f rentex

# enter in the container
# docker exec -it rentex sh
# docker exec -it rentex /bin/bash


# both services cant comunicate with each other because they are in different networks
# we can inspect the network and see the ip of the container
# docker network inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' rentex_default
# docker exec rentex cat /etc/hosts  <<-- para pegar o IP

